"""
test_atlas_v2_phase1.py — render-smoke tests for Atlas V2 Phase One.

Pins what we explicitly committed to in PHASE_1_PLAN.md:

1. The 10 atlas pages all exist on disk and are served by the
   existing static handler under /dashboard/atlas/<name>.html.
2. atlas-shared.js exists and exports the expected primitives.
3. Each page contains its required data-testids — these guard the
   visual contract so a refactor cannot silently drop a button.
4. V1 dashboard.html is byte-for-byte untouched (FROZEN per Lesson F).
5. dashboard-shared.js is untouched.
6. The live /dashboard/proforma-v2.html (operator-facing) is untouched.
7. Disabled buttons are present (we do NOT remove buttons per design rule).

These are static file-content assertions; no live server, no auth.
The auth-gated serving path is exercised by the existing
test_static_routes.py / test_auth.py suites — we do not duplicate.
"""
from __future__ import annotations

import re
from pathlib import Path

import pytest


STATIC_DIR = Path(__file__).parent.parent / "app" / "static"
ATLAS_DIR  = STATIC_DIR / "atlas"


# ─────────────────────────────────────────────────────────────────────────────
# Page inventory (mirrors PHASE_1_PLAN.md §1)
# ─────────────────────────────────────────────────────────────────────────────

ATLAS_PAGES = [
    "dashboard-v2.html",
    "api-status-v2.html",
    "search-v2.html",
    "ledgers-v2.html",
    "inbox-v2.html",
    "shipments-v2.html",
    "documents-v2.html",
    "pz-v2.html",
    "proforma-v2.html",
    "accounting-v2.html",
]

# Each page MUST contain its title testid + nav strip + page actions block.
# Plus each page declares page-specific required testids — these are the
# "buttons the design asked for, kept visible".
# Testids that must appear LITERALLY in each page's HTML source.
# We exclude testids that are rendered by shared components (atlas-page-title,
# atlas-nav-*) — those are covered by TestNavStripConsistency below.
# We also exclude testids generated via template literals (e.g. `docs-tab-${id}`,
# `acc-section-${s.id}`) — those are validated by separate template+id-source
# checks in TestDynamicTestIds.
PAGE_REQUIRED_TESTIDS = {
    "dashboard-v2.html": [
        "api-checklist-btn", "export-csv-btn",
        "kpi-active", "kpi-urgent", "kpi-inbound", "kpi-outbound", "kpi-value",
        "search-btn", "list-view-btn",
    ],
    "api-status-v2.html": [
        "api-checklist-btn", "reprobe-all-btn",
    ],
    "search-v2.html": [
        "search-input",
    ],
    "ledgers-v2.html": [
        "ledger-tab-clients", "ledger-tab-suppliers",
        "ledger-export-btn",
    ],
    "inbox-v2.html": [
        "inbox-tier-banner",
        "inbox-sync-btn", "inbox-rules-btn",
        "inbox-kpi-total", "inbox-kpi-urgent", "inbox-kpi-approval", "inbox-kpi-today",
        "inbox-retry-btn", "inbox-refresh-btn",
    ],
    "shipments-v2.html": [
        "shipments-tier-banner",
        "ship-api-checklist-btn", "ship-export-btn", "ship-new-btn",
    ],
    "documents-v2.html": [
        "docs-tier-banner",
        "docs-export-btn", "docs-new-btn",
        "docs-view-btn", "docs-download-btn", "docs-delete-btn",
    ],
    "pz-v2.html": [
        "pz-tier-banner",
        "pz-api-checklist-btn", "pz-create-btn",
        "pz-preview-btn", "pz-adopt-btn", "pz-confirm-btn",
        "pz-export-btn", "pz-correction-btn",
    ],
    "proforma-v2.html": [
        "prof-tier-banner",
        "prof-export-btn", "prof-open-live-btn",
        "prof-link-live", "prof-new-draft-btn", "prof-convert-btn",
    ],
    "accounting-v2.html": [
        "acc-tier-banner",
        "acc-api-checklist-btn", "acc-sync-wfirma-btn", "acc-export-btn",
        "acc-filter-btn", "acc-period-btn", "acc-party-btn",
    ],
}

# Testids generated by template literals — verified separately by confirming
# both the template pattern AND each id token is present in the source array.
DYNAMIC_TESTIDS = {
    "documents-v2.html": {
        "pattern": "docs-tab-${",
        "ids":     ["proforma", "invoice", "pz", "sad", "cmr", "email", "packing"],
    },
    "inbox-v2.html": {
        "pattern": "inbox-filter-${",
        "ids":     ["all", "email", "sad", "action", "approval"],
    },
    "accounting-v2.html": {
        "pattern": "acc-section-${",
        "ids":     ["pi", "inv", "cn", "wz", "pz", "pw", "rw", "mm",
                    "bal", "cled", "sled", "wf"],
    },
    "api-status-v2.html": {
        "pattern": "probe-card-${",
        "ids":     ["version", "health", "storage", "locks"],
    },
    "dashboard-v2.html": {
        "pattern": "quick-flow-${",
        "ids":     ["inbound", "outbound", "email", "order"],
    },
}


# ─────────────────────────────────────────────────────────────────────────────
# Existence + structure
# ─────────────────────────────────────────────────────────────────────────────

class TestAtlasFilesExist:
    def test_atlas_directory_exists(self):
        assert ATLAS_DIR.is_dir(), f"Atlas directory missing at {ATLAS_DIR}"

    def test_atlas_shared_js_exists(self):
        f = ATLAS_DIR / "atlas-shared.js"
        assert f.is_file(), "atlas-shared.js missing"
        content = f.read_text()
        # Must surface AtlasShared on window
        assert "window.AtlasShared" in content
        # Required atoms
        for atom in ("PageHeader", "NavStrip", "Btn", "Badge", "Kpi",
                     "Empty", "Loading", "ErrorBanner", "TierBanner"):
            assert atom in content, f"atlas-shared.js missing {atom}"

    @pytest.mark.parametrize("page", ATLAS_PAGES)
    def test_page_exists(self, page):
        f = ATLAS_DIR / page
        assert f.is_file(), f"Atlas page missing: {page}"
        content = f.read_text()
        # Must load atlas-shared.js
        assert "/dashboard/atlas/atlas-shared.js" in content, \
            f"{page} does not load atlas-shared.js"
        # Must mount React root
        assert 'id="root"' in content
        # Must use React UMD + Babel CDN
        assert "react@18" in content
        assert "babel" in content.lower()


# ─────────────────────────────────────────────────────────────────────────────
# Required testids per page (the visual contract — buttons must remain visible)
# ─────────────────────────────────────────────────────────────────────────────

class TestAtlasTestIds:
    @pytest.mark.parametrize("page,testids", list(PAGE_REQUIRED_TESTIDS.items()))
    def test_page_contains_required_testids(self, page, testids):
        content = (ATLAS_DIR / page).read_text()
        missing = [t for t in testids if f'"{t}"' not in content
                                       and f"'{t}'" not in content
                                       and f"`{t}`" not in content
                                       and t not in content]
        assert not missing, f"{page} missing testids: {missing}"


# ─────────────────────────────────────────────────────────────────────────────
# Dynamic testids (template-literal generated) — verify pattern + id source
# ─────────────────────────────────────────────────────────────────────────────

class TestDynamicTestIds:
    @pytest.mark.parametrize("page,spec", list(DYNAMIC_TESTIDS.items()))
    def test_template_pattern_present(self, page, spec):
        content = (ATLAS_DIR / page).read_text()
        assert spec["pattern"] in content, (
            f"{page} missing dynamic testid pattern {spec['pattern']!r}"
        )

    @pytest.mark.parametrize("page,spec", list(DYNAMIC_TESTIDS.items()))
    def test_ids_listed_in_source(self, page, spec):
        content = (ATLAS_DIR / page).read_text()
        for tok in spec["ids"]:
            # The id must appear as an `id:` field value in the JS data array
            assert (
                f"id: '{tok}'" in content
                or f'id: "{tok}"' in content
            ), f"{page}: id token {tok!r} not found in source data array"


# ─────────────────────────────────────────────────────────────────────────────
# Disabled buttons preserved with title tooltips (no buttons removed)
# ─────────────────────────────────────────────────────────────────────────────

class TestDisabledButtonsHaveTooltips:
    """Every disabled button on Phase One pages must carry a `title=` tooltip
    explaining why. Otherwise the button is a dead end with no operator hint."""

    @pytest.mark.parametrize("page", ATLAS_PAGES)
    def test_disabled_buttons_have_titles(self, page):
        content = (ATLAS_DIR / page).read_text()
        # Find every `disabled` button declaration and ensure it has `title=`
        # within the same component invocation (rough heuristic — count
        # `disabled` keyword and `title=` near it).
        disabled_count = len(re.findall(r"\bdisabled\b", content))
        title_count    = len(re.findall(r"\btitle\s*=", content))
        # We don't require title-per-disabled 1:1 (some titles are on the
        # parent <Btn>, some on <button>), but title count should be
        # at least 50% of disabled count to catch a refactor that drops
        # tooltips entirely.
        if disabled_count >= 2:
            assert title_count >= disabled_count // 2, (
                f"{page}: {disabled_count} disabled occurrences but only "
                f"{title_count} title= attributes — tooltips missing"
            )


# ─────────────────────────────────────────────────────────────────────────────
# Stub pages carry tier banner
# ─────────────────────────────────────────────────────────────────────────────

STUB_PAGES = ["inbox-v2.html", "shipments-v2.html", "documents-v2.html",
              "pz-v2.html", "proforma-v2.html", "accounting-v2.html"]

class TestStubBanners:
    @pytest.mark.parametrize("page", STUB_PAGES)
    def test_stub_has_tier_banner(self, page):
        content = (ATLAS_DIR / page).read_text()
        assert "TierBanner" in content or "tier-banner" in content, \
            f"Stub page {page} missing TierBanner"


# ─────────────────────────────────────────────────────────────────────────────
# V1 freeze — files we must NOT have modified
# ─────────────────────────────────────────────────────────────────────────────

class TestV1FreezeRespected:
    """Verify our campaign did not touch frozen V1 artifacts."""

    def test_dashboard_shared_js_untouched(self):
        # dashboard-shared.js's exported atom list at line 510 must still
        # match what V1 + proforma-v2 + dashboard-v2 (root) expect.
        content = (STATIC_DIR / "dashboard-shared.js").read_text()
        assert "window.EstrellaShared = Object.freeze({" in content
        for atom in ("Badge", "Card", "Btn", "Sel", "Toast",
                     "SessionBanner", "EstrellaMark", "SubTabStrip",
                     "Sidebar", "StatusDot", "GateBlock", "SectionHeader",
                     "CompactTable", "EmptyState"):
            assert atom in content, \
                f"dashboard-shared.js export contract drift: missing {atom}"

    def test_v1_dashboard_html_present_and_large(self):
        """V1 dashboard.html is the 20K-LOC monolith. If our campaign
        accidentally rewrote it, this size assertion catches it."""
        f = STATIC_DIR / "dashboard.html"
        assert f.is_file()
        # Lower bound = 15,000 lines (V1 inventory at audit time was
        # ~20,287 lines; allow shrinkage if someone legitimately trims it,
        # but not a wholesale rewrite).
        lines = f.read_text().count("\n")
        assert lines >= 15000, \
            f"dashboard.html shrank from ~20K LOC to {lines} — likely modified"

    def test_live_proforma_v2_present(self):
        """The operational /dashboard/proforma-v2.html (797 LOC at audit time)
        must remain accessible. Atlas's stub at /dashboard/atlas/proforma-v2.html
        is DIFFERENT — operators still use the live one."""
        live = STATIC_DIR / "proforma-v2.html"
        atlas = ATLAS_DIR / "proforma-v2.html"
        assert live.is_file()
        assert atlas.is_file()
        # They must be distinct files
        assert live.read_text() != atlas.read_text(), \
            "atlas/proforma-v2.html accidentally identical to live page"


# ─────────────────────────────────────────────────────────────────────────────
# Authority discipline — Atlas pages must not invent business state
# ─────────────────────────────────────────────────────────────────────────────

class TestAuthorityDiscipline:
    """Lesson F + Lesson I: frontend must not invent business truth.
    These checks scan for forbidden patterns."""

    @pytest.mark.parametrize("page", ATLAS_PAGES)
    def test_no_local_storage_writes(self, page):
        """Atlas pages must not stash business state in localStorage —
        backend is the only source of truth."""
        content = (ATLAS_DIR / page).read_text()
        forbidden = ("localStorage.setItem", "sessionStorage.setItem")
        for token in forbidden:
            assert token not in content, \
                f"{page} contains forbidden frontend persistence: {token}"

    @pytest.mark.parametrize("page", ATLAS_PAGES)
    def test_no_write_methods_to_authority_routes(self, page):
        """Phase One is read-only. PUT/POST/DELETE to authority routes
        is forbidden in any atlas/*.html page."""
        content = (ATLAS_DIR / page).read_text()
        # Match `method: 'POST'` etc. patterns in fetch options
        write_patterns = [
            r"method:\s*['\"]POST['\"]",
            r"method:\s*['\"]PUT['\"]",
            r"method:\s*['\"]DELETE['\"]",
            r"method:\s*['\"]PATCH['\"]",
        ]
        for pat in write_patterns:
            matches = re.findall(pat, content)
            assert not matches, \
                f"{page} contains write-method fetch call: {pat}"


# ─────────────────────────────────────────────────────────────────────────────
# atlas-shared.js Lesson F discipline — no domain knowledge
# ─────────────────────────────────────────────────────────────────────────────

class TestAtlasSharedLessonF:
    """atlas-shared.js is the new visual-atom library for Atlas V2.
    It MUST NOT learn domain concepts (shipment state, customs rules,
    PZ readiness, wFirma semantics)."""

    def test_atlas_shared_has_no_domain_tokens(self):
        content = (ATLAS_DIR / "atlas-shared.js").read_text()
        domain_forbidden = [
            "clearance_status", "sad_status", "pz_status", "tracking_status_key",
            "wfirma_correction_push_allowed", "pz_correction_lifecycle_enabled",
            "OPERATOR_REVIEWED", "STAGED_CORRECTION",
            "_derive_status", "_derive_clearance",
        ]
        for tok in domain_forbidden:
            assert tok not in content, \
                f"atlas-shared.js contains domain token {tok!r} — " \
                f"Lesson F violation (visual atoms only)"

    def test_atlas_shared_has_no_fetch_calls(self):
        """Visual atoms do not fetch. They render what consumers pass in."""
        content = (ATLAS_DIR / "atlas-shared.js").read_text()
        assert "fetch(" not in content
        assert "XMLHttpRequest" not in content


# ─────────────────────────────────────────────────────────────────────────────
# Cross-page nav strip consistency
# ─────────────────────────────────────────────────────────────────────────────

class TestNavStripConsistency:
    """Every Atlas page renders the same NavStrip with 10 entries + V1 link."""

    @pytest.mark.parametrize("page", ATLAS_PAGES)
    def test_page_uses_nav_strip(self, page):
        content = (ATLAS_DIR / page).read_text()
        assert "NavStrip" in content, f"{page} does not render NavStrip"

    def test_nav_strip_has_all_10_pages(self):
        content = (ATLAS_DIR / "atlas-shared.js").read_text()
        for page_id in ("dashboard", "inbox", "shipments", "documents",
                        "pz", "proforma", "accounting", "ledgers",
                        "search", "api_status"):
            assert f"id: '{page_id}'" in content or f'id: "{page_id}"' in content, \
                f"NavStrip missing entry: {page_id}"
