"""
golden_constants.py — Shipment 039–044 reference values
========================================================
Single source of truth for all pinned values used by the regression suite.

TREAT THIS FILE LIKE A LEDGER, NOT CONFIG.
Every value here has a specific source (workbook / NBP table / ZC429).
Changing a number without a validated source is an accounting error.

──────────────────────────────────────────────────────────────────────────────
CORRECT UPDATE SEQUENCE (must be followed in this order):

  1. Run ./verify.sh --full   → tests MUST fail before you edit this file.
     If they don't fail, the new batch is identical to the old one — stop.
  2. Validate the new batch manually against the workbook and ZC429.
  3. Edit this file. Add a change block (see template below).
  4. Run ./verify.sh --full   → tests must go green again.
  5. Commit golden_constants.py and test output together, nothing else.
     Use the commit message format below — no other format is acceptable.

DO NOT edit this file just to make tests pass.
Edit it only when you have a newly validated reference workbook.
──────────────────────────────────────────────────────────────────────────────

COMMIT MESSAGE FORMAT (required when this file changes):

  Update golden constants — shipment NNN–NNN
  MRN: <MRN from ZC429>
  NBP: Table XXX/A/NBP/YYYY (YYYY-MM-DD), 1 USD = X.XXXX PLN
  Validated against: PZ_calculation_template_NNN_NNN.xlsx (YYYY-MM-DD)

  Example:
    Update golden constants — shipment 045–050
    MRN: 26PL44302D009X1YZ2
    NBP: Table 082/A/NBP/2026 (2026-05-14), 1 USD = 3.7812 PLN
    Validated against: PZ_calculation_template_45_50.xlsx (2026-05-20)

The commit must include only: golden_constants.py and the test run output.
No source code changes — if code changed, that is a separate commit.
──────────────────────────────────────────────────────────────────────────────

CHANGE LOG — one block per validated batch update:

  # [2026-04-22] Shipment 039–044 — initial golden reference
  # Source : PZ_calculation_template_39_44.xlsx (validated 2026-04-22)
  # NBP    : Table 069/A/NBP/2026, date 2026-04-09, 1 USD = 3.6506 PLN
  # ZC429  : MRN 26PL44302D008N8OR0 / LRN 26S00Q8O0S
  # Changed: initial values — all fields set for the first time

  # [YYYY-MM-DD] Shipment NNN–NNN — <brief reason>
  # Source : PZ_calculation_template_NNN_NNN.xlsx (validated YYYY-MM-DD)
  # NBP    : Table XXX/A/NBP/YYYY, date YYYY-MM-DD, 1 USD = X.XXXX PLN
  # ZC429  : MRN XXXXXXXXXXXXXXXX / LRN XXXXXXXXXX
  # Changed: <list what changed, e.g. "GOLDEN_RATE, EXPECTED_RAZEM_NETTO, GOLDEN_ROW_HASH">
──────────────────────────────────────────────────────────────────────────────
"""

# ── Exchange rate ─────────────────────────────────────────────────────────────
# NBP Table A, 2026-04-09 (one working day before invoice date 10-04-2026).
# Used as --rate override in all e2e tests to avoid NBP API dependency.
GOLDEN_RATE: float = 3.6506

# ── Batch totals (from PZ_calculation_template_39_44.xlsx, validated 2026-04-22) ──
EXPECTED_INVOICE_COUNT: int   = 6
EXPECTED_LINES:         int   = 16
EXPECTED_RAZEM_NETTO:   float = 49668.46   # workbook: 49668.462
EXPECTED_RAZEM_BRUTTO:  float = 61092.21   # workbook: 61092.208
EXPECTED_DUTY_A00:      float = 1225.00

# ── Per-line unit Cena netto (PLN) ────────────────────────────────────────────
# Index matches row order in final PZ output.  Tolerance used in tests: ±0.05 PLN.
EXPECTED_UNIT_NET: list = [
    802.26,    # L1  DIA&CLS PENDANT        × 2   (invoice 039)
    1861.70,   # L2  Diamond Studded RING   × 9   (invoice 039)
    864.26,    # L3  DIA&CLS EARRINGS       × 1   (invoice 039)
    2324.10,   # L4  Diamond Studded EARRINGS × 2 (invoice 039)
    933.48,    # L5  Plain 18KT RING        × 1   (invoice 040)
    1113.90,   # L6  Diamond Studded RING   × 1   (invoice 040)
    761.26,    # L7  DIA&CLS PENDANT        × 1   (invoice 041)
    3493.49,   # L8  DIA&CLS RING           × 2   (invoice 041)
    1844.10,   # L9  Diamond Studded EARRINGS × 1.5 (invoice 041)
    3214.62,   # L10 DIA&CLS EARRINGS       × 1   (invoice 041)
    698.68,    # L11 Diamond Studded RING   × 3   (invoice 042)
    5458.50,   # L12 Lab Grown 18KT BRACELET × 1  (invoice 042)
    365.17,    # L13 Plain 14KT PENDANT     × 1   (invoice 043)
    19.02,     # L14 Silver PENDANT         × 1   (invoice 043)
    1222.77,   # L15 Lab Grown 14KT RING    × 1   (invoice 044)
    858.29,    # L16 Plain 14KT RING        × 1   (invoice 044)
]

# ── Per-line quantities ───────────────────────────────────────────────────────
EXPECTED_QUANTITIES: list = [2, 9, 1, 2, 1, 1, 1, 2, 1.5, 1, 3, 1, 1, 1, 1, 1]

# ── Description rules (family, item_type, must_contain) ──────────────────────
DESC_RULES: list = [
    # (family, item_type, must_contain) — tested against build_pl_name() output
    ("Diamond / Colour Stone Studded", "PENDANT",  "kamieniami"),
    ("Diamond / Colour Stone Studded", "RING",     "kamieniami"),
    ("Diamond / Colour Stone Studded", "EARRINGS", "kamieniami"),
    ("Diamond Studded",                "RING",     "wysadzany"),
    ("Diamond Studded",                "EARRINGS", "wysadzane"),
    ("Lab Grown Diamond",              "BRACELET", "hodowanymi"),
    ("Lab Grown Diamond",              "RING",     "hodowanymi"),  # plural: "hodowanymi laboratoryjnie"
    ("Plain",                          "RING",     "pierścionek"), # new builder: "pierścionek ze złota…"
    ("Silver Plain",                   "PENDANT",  "srebrny"),     # new builder: lowercase
]

# ── Sanity bounds ─────────────────────────────────────────────────────────────
DUTY_RATE_MAX_PCT: float = 20.0
QTY_MAX_VALID:     int   = 1000

# ── Golden row hash ───────────────────────────────────────────────────────────
# SHA-256 of json.dumps([_stable(row) for row in rows], sort_keys=True, ensure_ascii=False)
# where _stable() rounds all PLN values to 4dp.
# Computed from the validated golden batch at GOLDEN_RATE.
# Any change to row count, order, descriptions, quantities, or PLN values
# will produce a different hash and fail the test.
GOLDEN_ROW_HASH: str = "a778732f8a904834e67ef19d729a62f7db99b50ed598aebb3c2d7797f9bce28e"

# ── Blocked correction-log phrases ───────────────────────────────────────────
# If any entry in corrections_log contains one of these phrases, the golden
# batch test fails. "Filename date differs" warnings are expected and allowed.
# Operational rule: never generate a live PZ if corrections_log contains any
# of these phrases — it means the parser fell back or a value was implausible.
BLOCKED_CORRECTION_PHRASES: list = [
    "reparsed",
    "not found",
    "suspicious",
    "failed",
    "invalid",
    "manual entry",
    "could not",
]

# ── Note line 4 ──────────────────────────────────────────────────────────────
# Derived from ZC429 Zgłaszający field: "AGENCJA CELNA SPEDYCJA KUŹMICZ K."
# settlement_mode = "standard", agent parsed from ZC429 → "Odprawa celna przez: <agent>"
GOLDEN_NOTE_4: str = "Odprawa celna przez: AGENCJA CELNA SPEDYCJA KUŹMICZ K."

# Batch meta used when running the golden e2e test.
# DHL is the carrier but the agency (Zgłaszający) takes precedence in standard mode.
GOLDEN_BATCH_META: dict = {
    "settlement_mode":      "standard",
    "prefer_carrier_label": False,
    "carrier_name":         "DHL EXPRESS (POLAND) SP. Z O.O.",
}

# ── CIF reconciliation ────────────────────────────────────────────────────────
# Sum of all invoice CIFs must match the ZC429 declared invoice value within
# this tolerance. A larger gap means a missing/duplicate invoice or a parse error.
CIF_RECONCILIATION_TOLERANCE_USD: float = 1.0
