"""
guards.py — Shipment pipeline enforcement guards
=================================================
Every pipeline action must pass its guard before executing.
Guards raise HTTPException with a structured error body.

Error body: {"guard": "<name>", "error": "<message>", "code": "<GUARD_CODE>"}

Advisory mode (settings.advisory_gates_enabled = True):
  The three workflow guards (guard_pz_requires_sad, guard_dhl_requires_email,
  guard_proforma_export_prerequisites) become advisory — they return an advisory
  dict instead of raising, allowing the pipeline to continue with a warning.
  The four wFirma write flags remain hard-gated regardless.
"""
from __future__ import annotations
from typing import Optional
from fastapi import HTTPException


def _guard_error(code: str, message: str) -> HTTPException:
    prefix = code.split("_")[0].lower()
    return HTTPException(
        status_code=422,
        detail={"guard": prefix, "error": message, "code": code},
    )


def _advisory_mode() -> bool:
    """Return True when advisory_gates_enabled is set in settings."""
    try:
        from ..core.config import settings as _s
        return bool(_s.advisory_gates_enabled)
    except Exception:
        return False


def _make_advisory(code: str, message: str) -> dict:
    """Build an advisory warning dict (NOT an HTTPException)."""
    return {
        "advisory": True,
        "code": code,
        "message": message,
        "action": "review and approve in Inbox to continue, or supply the missing data",
    }


# Valid trigger sources — every action must declare one
VALID_TRIGGER_SOURCES = frozenset(
    ["user", "email", "document", "system", "bot", "dashboard", "api",
     "auto_idle", "auto_ready", "manual", "dhl_monitor"]
)

# Forbidden status transitions: {current_status: [forbidden_targets]}
_FORBIDDEN_TRANSITIONS: dict[str, list[str]] = {
    "success":  ["awaiting_dhl_email", "collecting", "ready"],
    "blocked":  ["success", "partial"],
    "partial":  ["collecting", "ready"],
    "failed":   ["success", "partial", "blocked"],
}


def guard_pz_requires_sad(audit: dict) -> Optional[dict]:
    """Check PZ execution requires SAD (ZC429) data.

    Hard mode (default): raises HTTP 422 when SAD is absent.
    Advisory mode (advisory_gates_enabled=True): returns an advisory dict
      instead of raising, allowing PZ to proceed with a warning.

    Returns None when the check passes (no advisory).
    Returns advisory dict when in advisory mode and SAD is absent.
    Raises HTTPException(422) when in hard mode and SAD is absent.

    The PZ_ALREADY_PROCESSED guard remains hard in both modes.
    """
    inputs = audit.get("inputs") or {}
    has_pdf = bool(inputs.get("zc429"))

    # XML path: customs parsed from ZC429 XML → mrn present in customs_declaration or zc429 dict
    cd = audit.get("customs_declaration") or {}
    zc429_dict = audit.get("zc429") or {}
    has_xml = bool(cd.get("mrn") or zc429_dict.get("mrn"))

    if not has_pdf and not has_xml:
        msg = (
            "PZ requires SAD (ZC429) data. Upload ZC429 or ensure customs "
            "declaration XML has been parsed."
        )
        if _advisory_mode():
            return _make_advisory("PZ_NO_SAD", msg)
        raise _guard_error("PZ_NO_SAD", msg)

    # PZ_ALREADY_PROCESSED remains hard — this is a data-integrity guard, not a
    # workflow gate. Allowing double-processing without a reset is unsafe.
    if audit.get("status") == "blocked":
        raise _guard_error(
            "PZ_ALREADY_PROCESSED",
            "Batch is in state 'blocked'. Re-processing not allowed without reset.",
        )
    return None


def guard_dhl_requires_email(audit: dict, admin_override: bool = False) -> Optional[dict]:
    """Check DSK/description generation requires a DHL customs email.

    Hard mode (default): raises HTTP 422 when no email/ticket/status present.
    Advisory mode (advisory_gates_enabled=True): returns advisory dict instead.

    Returns None when the check passes.
    Returns advisory dict in advisory mode when email is absent.
    Raises HTTPException(422) in hard mode when email is absent.
    """
    if admin_override:
        return None
    clearance_ok = {
        "dhl_email_received", "clearance_in_progress", "dhl_clearance_required",
        "external_broker_required", "polish_description_generated", "dsk_generated",
        "reply_queued", "sent_to_dhl",
        # Shipments awaiting a DHL email (pre-email state) may still need
        # customs documents generated by the user before the email arrives.
        "awaiting_dhl_customs_email", "awaiting_dhl_email",
    }
    if audit.get("clearance_status") in clearance_ok:
        return None
    if audit.get("dhl_ticket"):
        return None
    # Manual admin override: admin marked email received via dashboard modal
    dhl_email = audit.get("dhl_email") or {}
    if dhl_email.get("received") is True:
        return None

    msg = "Clearance action requires a DHL customs email (T#... ticket). No email received yet."
    if _advisory_mode():
        return _make_advisory("DHL_NO_EMAIL", msg)
    raise _guard_error("DHL_NO_EMAIL", msg)


def guard_sad_requires_batch(audit: dict) -> None:
    """Block SAD parsing if no AWB/shipment batch exists."""
    if not audit.get("batch_id"):
        raise _guard_error(
            "SAD_NO_BATCH",
            "Shipment batch must exist before customs intake. Create a batch with invoices first.",
        )
    inputs = audit.get("inputs") or {}
    has_content = audit.get("tracking_no") or inputs.get("invoices") or inputs.get("invoice_files")
    if not has_content:
        raise _guard_error(
            "SAD_EMPTY_BATCH",
            "Batch exists but has no invoices or AWB. Upload invoices before customs intake.",
        )


def guard_status_transition(current: str, target: str) -> None:
    """Prevent invalid status transitions."""
    forbidden = _FORBIDDEN_TRANSITIONS.get(current, [])
    if target in forbidden:
        raise _guard_error(
            "INVALID_TRANSITION",
            f"Invalid status transition: {current} → {target}. "
            f"Current state '{current}' cannot move to '{target}'.",
        )


def guard_trigger_declared(trigger_source: str) -> None:
    """Every action must declare its trigger source."""
    if not trigger_source or trigger_source not in VALID_TRIGGER_SOURCES:
        raise _guard_error(
            "TRIGGER_UNDECLARED",
            f"trigger_source must be declared. Got: {repr(trigger_source)}. "
            f"Valid: {sorted(VALID_TRIGGER_SOURCES)}",
        )


def guard_batch_is_primary_unit(audit: dict) -> None:
    """All actions require an active shipment batch."""
    if not audit.get("batch_id"):
        raise _guard_error(
            "NO_BATCH_ANCHOR",
            "All actions require an active shipment batch (AWB). No batch found.",
        )
